test github action

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -24,17 +24,17 @@ jobs:
           fetch-depth: 0 # Needed for MinVer to access tags
 
       # If this is a tag push, only continue if the tag points to a commit reachable from main
-      - name: Determine if tag target is on main
-        if: startsWith(github.ref, 'refs/tags/')
-        run: |
-          TAG_SHA=$(git rev-list -n 1 "$GITHUB_REF_NAME")
-          if ! git merge-base --is-ancestor "$TAG_SHA" origin/main; then
-            echo "Tag $GITHUB_REF_NAME is not on main, aborting."
-            gh run cancel ${{ github.run_id }}
-            gh run watch ${{ github.run_id }}
-          fi
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #- name: Determine if tag target is on main
+      #  if: startsWith(github.ref, 'refs/tags/')
+      #  run: |
+      #    TAG_SHA=$(git rev-list -n 1 "$GITHUB_REF_NAME")
+      #    if ! git merge-base --is-ancestor "$TAG_SHA" origin/main; then
+      #      echo "Tag $GITHUB_REF_NAME is not on main, aborting."
+      #      gh run cancel ${{ github.run_id }}
+      #      gh run watch ${{ github.run_id }}
+      #    fi
+      #  env:
+      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Calculate version with MinVer
         run: echo "MINVERVERSIONOVERRIDE=$(bash calculate-version.sh)" >> "$GITHUB_ENV"
@@ -46,7 +46,8 @@ jobs:
         id: tags
         shell: bash
         run: |
-          IMAGE="ghcr.io/${{ github.repository }}"
+          #IMAGE="ghcr.io/${{ github.repository }}"
+          IMAGE="ghcr.io/${{ github.repository }}-dev"
           VERSION="$MINVERVERSIONOVERRIDE"
 
           # Always add MinVer version and :current
